name: ✨ Feature Request
description: Suggest a new feature or enhancement for CertMonitor
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide detailed information to help us understand your request.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested
          required: true
        - label: I have read the documentation to ensure this feature doesn't already exist
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like in detail
      placeholder: "I would like CertMonitor to..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - New validator
        - Protocol support
        - Certificate parsing
        - API enhancement
        - Performance improvement
        - Documentation
        - Testing
        - Developer experience
        - Configuration/setup
        - Error handling
        - Other
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: "In my environment, I need to..."
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas on how this could be implemented? (Optional)
      placeholder: "This could be implemented by..."
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Provide examples of how the feature would be used
      render: python
      placeholder: |
        # Example usage
        from certmonitor import CertMonitor
        
        # Your proposed API here
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternative approaches could be..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to write tests for this feature
        - label: I would be willing to write documentation for this feature
        - label: I would be willing to help with code review

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information...
    validations:
      required: false
